Added caching, removed build phase and added report action

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -3,7 +3,7 @@ name: Java CI with Maven
 on: [push, pull_request]
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
     services:
       mariadb:
@@ -27,6 +27,7 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
+          cache: 'maven'
 
       - name: Install MySQL client and Load Database Schema
         run: |
@@ -36,8 +37,11 @@ jobs:
           mysql -h 127.0.0.1 -u root --password=root -e "GRANT ALL PRIVILEGES ON *.* TO 'mopat'@'%'; FLUSH PRIVILEGES;"
           mysql -h 127.0.0.1 -u root --password=root < db/installationInitTest.sql
 
-      - name: Build with Maven
-        run: mvn -B clean package --file pom.xml
-
       - name: Test with Maven
         run: mvn -B test --file pom.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
